/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './file-drop-module';
import * as import2 from '@angular/core/src/di/injector';
class FileDropModuleInjector extends import0.NgModuleInjector<import1.FileDropModule> {
  _FileDropModule_0:import1.FileDropModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.FileDropModule {
    this._FileDropModule_0 = new import1.FileDropModule();
    return this._FileDropModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.FileDropModule)) { return this._FileDropModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const FileDropModuleNgFactory:import0.NgModuleFactory<import1.FileDropModule> = new import0.NgModuleFactory(FileDropModuleInjector,import1.FileDropModule);